export const opportunityTypeChoices = [
    { value: 'Test', label: 'Test' },
    { value: 'Review', label: 'Review' },
    { value: 'Shout Out', label: 'Shout Out' },
    { value: 'Product Placement', label: 'Product Placement' },
];

export const countryChoices = [
    { value: 'GB', label: 'United Kingdom' },
    { value: 'US', label: 'United States' },
    { value: 'CA', label: 'Canada' },
    { value: 'AU', label: 'Australia' },
    { value: 'NZ', label: 'New Zealand' },
    { value: 'IE', label: 'Ireland' },
    { value: 'SG', label: 'Singapore' },
    { value: 'HK', label: 'Hong Kong' },
    { value: 'JP', label: 'Japan'}
];

  
export const industryChoices = [
    { value: 'Internet, Software & IT', label: 'Internet, Software & IT' },
    { value: 'Aerospace & Defence', label: 'Aerospace & Defence' },
    { value: 'Consumer Goods & Services', label: 'Consumer Goods & Services' },
    { value: 'Gardening & Outdoors', label: 'Gardening & Outdoors' },
    { value: 'Consulting & Business Services', label: 'Consulting & Business Services' },
    { value: 'Entertainment & Leisure', label: 'Entertainment & Leisure' },
    { value: 'Fashion & Cosmetics', label: 'Fashion & Cosmetics' },
    { value: 'Health & Fitness', label: 'Health & Fitness' },
    { value: 'Music & Film', label: 'Music & Film' },
    { value: 'Retail', label: 'Retail' },
    { value: 'Charity & Fundraising', label: 'Charity & Fundraising' },
    { value: 'Education & Schools', label: 'Education & Schools' },
    { value: 'Computers & Electronics', label: 'Computers & Electronics' },
    { value: 'Insurance', label: 'Insurance' },
    { value: 'Banks & Financial Services', label: 'Banks & Financial Services' },
    { value: 'Transport & Freight', label: 'Transport & Freight' },
    { value: 'Construction', label: 'Construction' },
    { value: 'Telecommunications', label: 'Telecommunications' },
    { value: 'Restaurants & Cafes', label: 'Restaurants & Cafes' },
    { value: 'Pharmaceuticals', label: 'Pharmaceuticals' },
    { value: 'Hospitality & Catering', label: 'Hospitality & Catering' },
    { value: 'Food & Beverages', label: 'Food & Beverages' },
    { value: 'Healthcare', label: 'Healthcare' },
    { value: 'Art & Design', label: 'Art & Design' },
    { value: 'Media, News & Publishing', label: 'Media, News & Publishing' },
    { value: 'Sports', label: 'Sports' },
];
  
export const tagChoices = [
  { id: "1", value: "Gaming Computers", label: "Gaming Computers" },
  { id: "2", value: "Social Media", label: "Social Media" },
  { id: "3", value: "Programming", label: "Programming" },
  { id: "4", value: "Accounting", label: "Accounting" },
  { id: "5", value: "Avionics", label: "Avionics" },
  { id: "6", value: "Sports", label: "Sports" },
  { id: "7", value: "Camping", label: "Camping" },
  { id: "8", value: "Digital Marketing Services", label: "Digital Marketing Services" },
  { id: "9", value: "Events", label: "Events" },
  { id: "10", value: "Floristary", label: "Floristary" },
  { id: "11", value: "Gift Shop", label: "Gift Shop" },
  { id: "12", value: "Wellbeing", label: "Wellbeing" },
  { id: "13", value: "Jewellery", label: "Jewellery" },
  { id: "14", value: "Legal Services", label: "Legal Services" },
  { id: "15", value: "Music Management & Promotion", label: "Music Management & Promotion" },
  { id: "16", value: "Newsagents", label: "Newsagents" },
  { id: "17", value: "Online Learning", label: "Online Learning" },
  { id: "18", value: "Visitor Management Software", label: "Visitor Management Software" },
  { id: "19", value: "Removal Services", label: "Removal Services" },
  { id: "20", value: "Workwear & PPE Charity", label: "Workwear & PPE Charity" },
  { id: "21", value: "University", label: "University" },
  { id: "22", value: "Operational Services", label: "Operational Services" },
  { id: "23", value: "Defensive Systems", label: "Defensive Systems" },
  { id: "24", value: "Clothing Retail", label: "Clothing Retail" },
  { id: "25", value: "Sports Retail", label: "Sports Retail" },
  { id: "26", value: "Semiconductors", label: "Semiconductors" },
  { id: "27", value: "Health Insurance", label: "Health Insurance" },
  { id: "28", value: "Grocery Retail", label: "Grocery Retail" },
  { id: "29", value: "Banking", label: "Banking" },
  { id: "30", value: "Cycling", label: "Cycling" },
  { id: "31", value: "Index Funds", label: "Index Funds" },
  { id: "32", value: "Airlines", label: "Airlines" },
  { id: "33", value: "Builders Merchants", label: "Builders Merchants" },
  { id: "34", value: "DIY Retailers", label: "DIY Retailers" },
  { id: "35", value: "Gambling", label: "Gambling" },
  { id: "36", value: "Smartphones & Tablets", label: "Smartphones & Tablets" },
  { id: "37", value: "Cafe", label: "Cafe" },
  { id: "38", value: "Security Services", label: "Security Services" },
  { id: "39", value: "Vaccines", label: "Vaccines" },
  { id: "40", value: "Budget Hotel", label: "Budget Hotel" },
  { id: "41", value: "Business Process Outsourcing", label: "Business Process Outsourcing" },
  { id: "42", value: "Car Insurance", label: "Car Insurance" },
  { id: "43", value: "Life Insurance", label: "Life Insurance" },
  { id: "44", value: "Chocolate Manufactures", label: "Chocolate Manufactures" },
  { id: "45", value: "Luxury Clothing", label: "Luxury Clothing" },
  { id: "46", value: "Model", label: "Model" },
  { id: "47", value: "Chef", label: "Chef" },
  { id: "48", value: "Entrepreneur", label: "Entrepreneur" },
  { id: "49", value: "Financial Advisor", label: "Financial Advisor" },
  { id: "50", value: "Luxury Hotel", label: "Luxury Hotel" },
  { id: "51", value: "Tech Reviews", label: "Tech Reviews" },
  { id: "52", value: "Healthcare Professional", label: "Healthcare Professional" },
  { id: "53", value: "Aviation", label: "Aviation" },
  { id: "54", value: "Products Reviews", label: "Products Reviews" },
  { id: "55", value: "Education Journalism", label: "Education Journalism" },
  { id: "56", value: "R&B Music", label: "R&B Music" },
  { id: "57", value: "Rapper", label: "Rapper" },
  { id: "58", value: "Athlete Cycling", label: "Athlete Cycling" },
  { id: "59", value: "Esports", label: "Esports" },
  { id: "60", value: "Pop Music", label: "Pop Music" },
  { id: "61", value: "Private Tuition", label: "Private Tuition" },
  { id: "62", value: "Tennis", label: "Tennis" },
  { id: "63", value: "Food Blog", label: "Food Blog" },
  { id: "64", value: "Makeup", label: "Makeup" },
  { id: "65", value: "Languages", label: "Languages" },
  { id: "66", value: "Donation Collections", label: "Donation Collections" },
  { id: "67", value: "B&B Hotel", label: "B&B Hotel" },
  { id: "68", value: "DIY & Repairs", label: "DIY & Repairs" },
  { id: "69", value: "Digital Ocean", label: "Digital Ocean" },
  { id: "70", value: "Gyms", label: "Gyms" },
  { id: "71", value: "Nutrition", label: "Nutrition" },
  { id: "72", value: "Physiotherapy", label: "Physiotherapy" },
  { id: "73", value: "Football", label: "Football" },
  { id: "74", value: "Rugby", label: "Rugby" },
  { id: "75", value: "Mortgages", label: "Mortgages" },
  { id: "76", value: "Business Loans", label: "Business Loans" },
  { id: "77", value: "Gardening Tools", label: "Gardening Tools" },
  { id: "78", value: "Freelance Services", label: "Freelance Services" },
  { id: "79", value: "Cricket", label: "Cricket" },
  { id: "80", value: "Vitamin Suppliments", label: "Vitamin Suppliments" },
  { id: "81", value: "Sports Bar", label: "Sports Bar" },
  { id: "82", value: "Cryptocurrency", label: "Cryptocurrency" }
];


const DUMMY_DATA = {
  opportunity_type: "Shout Out",
  industry: "Aerospace & Defence",
  country: "CL",
  latitude: -30.0,
  longitude: -71.0,
  businessSlider: 0.6,
  influencerSlider: 0.8,
  individualSlider: 0.3,
  opportunityTypeSlider: 0.7,
  industrySlider: 1,
  countrySlider: 0.5,
  radius: 100,
  radiusSlider: 0.6,
  tagEffectSlider: 0.6,
  tags: [
    { name: "Nutrition", slider: 0.7 },
    { name: "Makeup", slider: 0.5 }
  ],
  specializedTags: [
    { name: "Health Insurance", slider: 0.8 },
    { name: "Gyms", slider: 0.6 }
  ],
  isApply: false,
  origin: "search",
  description: "This is a sample search query"
};