export const opportunityTypeChoices = [
    { value: 'Test', label: 'Test' },
    { value: 'Review', label: 'Review' },
    { value: 'Shout Out', label: 'Shout Out' },
    { value: 'Product Placement', label: 'Product Placement' },
];

export const countryChoices = [
    { value: 'GB', label: 'United Kingdom' },
    { value: 'US', label: 'United States' },
    { value: 'CA', label: 'Canada' },
    { value: 'AU', label: 'Australia' },
    { value: 'NZ', label: 'New Zealand' },
    { value: 'IE', label: 'Ireland' },
    { value: 'SG', label: 'Singapore' },
    { value: 'HK', label: 'Hong Kong' },
    { value: 'JP', label: 'Japan'}
];

  
export const industryChoices = [
    { value: 'Internet, Software & IT', label: 'Internet, Software & IT' },
    { value: 'Aerospace & Defence', label: 'Aerospace & Defence' },
    { value: 'Consumer Goods & Services', label: 'Consumer Goods & Services' },
    { value: 'Gardening & Outdoors', label: 'Gardening & Outdoors' },
    { value: 'Consulting & Business Services', label: 'Consulting & Business Services' },
    { value: 'Entertainment & Leisure', label: 'Entertainment & Leisure' },
    { value: 'Fashion & Cosmetics', label: 'Fashion & Cosmetics' },
    { value: 'Health & Fitness', label: 'Health & Fitness' },
    { value: 'Music & Film', label: 'Music & Film' },
    { value: 'Retail', label: 'Retail' },
    { value: 'Charity & Fundraising', label: 'Charity & Fundraising' },
    { value: 'Education & Schools', label: 'Education & Schools' },
    { value: 'Computers & Electronics', label: 'Computers & Electronics' },
    { value: 'Insurance', label: 'Insurance' },
    { value: 'Banks & Financial Services', label: 'Banks & Financial Services' },
    { value: 'Transport & Freight', label: 'Transport & Freight' },
    { value: 'Construction', label: 'Construction' },
    { value: 'Telecommunications', label: 'Telecommunications' },
    { value: 'Restaurants & Cafes', label: 'Restaurants & Cafes' },
    { value: 'Pharmaceuticals', label: 'Pharmaceuticals' },
    { value: 'Hospitality & Catering', label: 'Hospitality & Catering' },
    { value: 'Food & Beverages', label: 'Food & Beverages' },
    { value: 'Healthcare', label: 'Healthcare' },
    { value: 'Art & Design', label: 'Art & Design' },
    { value: 'Media, News & Publishing', label: 'Media, News & Publishing' },
    { value: 'Sports', label: 'Sports' },
];
  
export const tagChoices = [
    { value: 'Gaming Computers', label: 'Gaming Computers' },
    { value: 'Social Media', label: 'Social Media' },
    { value: 'Programming', label: 'Programming' },
    { value: 'Accounting', label: 'Accounting' },
    { value: 'Avionics', label: 'Avionics' },
    { value: 'Sports', label: 'Sports' },
    { value: 'Camping', label: 'Camping' },
    { value: 'Digital Marketing Services', label: 'Digital Marketing Services' },
    { value: 'Events', label: 'Events' },
    { value: 'Floristary', label: 'Floristary' },
    { value: 'Gift Shop', label: 'Gift Shop' },
    { value: 'Wellbeing', label: 'Wellbeing' },
    { value: 'Jewellery', label: 'Jewellery' },
    { value: 'Legal Services', label: 'Legal Services' },
    { value: 'Music Management & Promotion', label: 'Music Management & Promotion' },
    { value: 'Newsagents', label: 'Newsagents' },
    { value: 'Online Learning', label: 'Online Learning' },
    { value: 'Visitor Management Software', label: 'Visitor Management Software' },
    { value: 'Removal Services', label: 'Removal Services' },
    { value: 'Workwear & PPE Charity', label: 'Workwear & PPE Charity' },
    { value: 'University', label: 'University' },
    { value: 'Operational Services', label: 'Operational Services' },
    { value: 'Defensive Systems', label: 'Defensive Systems' },
    { value: 'Clothing Retail', label: 'Clothing Retail' },
    { value: 'Sports Retail', label: 'Sports Retail' },
    { value: 'Semiconductors', label: 'Semiconductors' },
    { value: 'Health Insurance', label: 'Health Insurance' },
    { value: 'Grocery Retail', label: 'Grocery Retail' },
    { value: 'Banking', label: 'Banking' },
    { value: 'Cycling', label: 'Cycling' },
    { value: 'Index Funds', label: 'Index Funds' },
    { value: 'Airlines', label: 'Airlines' },
    { value: 'Builders Merchants', label: 'Builders Merchants' },
    { value: 'DIY Retailers', label: 'DIY Retailers' },
    { value: 'Gambling', label: 'Gambling' },
    { value: 'Smartphones & Tablets', label: 'Smartphones & Tablets' },
    { value: 'Cafe', label: 'Cafe' },
    { value: 'Security Services', label: 'Security Services' },
    { value: 'Vaccines', label: 'Vaccines' },
    { value: 'Budget Hotel', label: 'Budget Hotel' },
    { value: 'Business Process Outsourcing', label: 'Business Process Outsourcing' },
    { value: 'Car Insurance', label: 'Car Insurance' },
    { value: 'Life Insurance', label: 'Life Insurance' },
    { value: 'Chocolate Manufactures', label: 'Chocolate Manufactures' },
    { value: 'Luxury Clothing', label: 'Luxury Clothing' },
    { value: 'Model', label: 'Model' },
    { value: 'Chef', label: 'Chef' },
    { value: 'Entrepreneur', label: 'Entrepreneur' },
    { value: 'Financial Advisor', label: 'Financial Advisor' },
    { value: 'Luxury Hotel', label: 'Luxury Hotel' },
    { value: 'Tech Reviews', label: 'Tech Reviews' },
    { value: 'Healthcare Professional', label: 'Healthcare Professional' },
    { value: 'Aviation', label: 'Aviation' },
    { value: 'Products Reviews', label: 'Products Reviews' },
    { value: 'Education Journalism', label: 'Education Journalism' },
    { value: 'R&B Music', label: 'R&B Music' },
    { value: 'Rapper', label: 'Rapper' },
    { value: 'Athlete Cycling', label: 'Athlete Cycling' },
    { value: 'Esports', label: 'Esports' },
    { value: 'Pop Music', label: 'Pop Music' },
    { value: 'Private Tuition', label: 'Private Tuition' },
    { value: 'Tennis', label: 'Tennis' },
    { value: 'Food Blog', label: 'Food Blog' },
    { value: 'Makeup', label: 'Makeup' },
    { value: 'Languages', label: 'Languages' },
    { value: 'Donation Collections', label: 'Donation Collections' },
    { value: 'B&B Hotel', label: 'B&B Hotel' },
    { value: 'DIY & Repairs', label: 'DIY & Repairs' },
    { value: 'Digital Ocean', label: 'Digital Ocean' },
    { value: 'Gyms', label: 'Gyms' },
    { value: 'Nutrition', label: 'Nutrition' },
    { value: 'Physiotherapy', label: 'Physiotherapy' },
    { value: 'Football', label: 'Football' },
    { value: 'Rugby', label: 'Rugby' },
    { value: 'Mortgages', label: 'Mortgages' },
    { value: 'Business Loans', label: 'Business Loans' },
    { value: 'Gardening Tools', label: 'Gardening Tools' },
    { value: 'Freelance Services', label: 'Freelance Services' },
    { value: 'Cricket', label: 'Cricket' },
    { value: 'Vitamin Suppliments', label: 'Vitamin Suppliments' },
    { value: 'Sports Bar', label: 'Sports Bar' },
    { value: 'Cryptocurrency', label: 'Cryptocurrency' },
];

const DUMMY_DATA = {
  opportunity_type: "Shout Out",
  industry: "Aerospace & Defence",
  country: "CL",
  latitude: -30.0,
  longitude: -71.0,
  businessSlider: 0.6,
  influencerSlider: 0.8,
  individualSlider: 0.3,
  opportunityTypeSlider: 0.7,
  industrySlider: 1,
  countrySlider: 0.5,
  radius: 100,
  radiusSlider: 0.6,
  tagEffectSlider: 0.6,
  tags: [
    { name: "Nutrition", slider: 0.7 },
    { name: "Makeup", slider: 0.5 }
  ],
  specializedTags: [
    { name: "Health Insurance", slider: 0.8 },
    { name: "Gyms", slider: 0.6 }
  ],
  isApply: false,
  origin: "search",
  description: "This is a sample search query"
};